# Generated by Django 3.2.8 on 2021-10-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('question_type', models.CharField(choices=[('1', 'ответ с выбором одного варианта'), ('2', 'ответ с выбором одного варианта'), ('3', 'ответ с выбором нескольких вариантов')], default='1', max_length=100)),
            ],
        ),
    ]
