# Generated by Django 3.2.8 on 2021-10-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('description', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quiz_id',
            field=models.IntegerField(default=1),
        ),
    ]
