# Generated by Django 3.2.8 on 2021-10-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_quiz_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='end',
            field=models.DateField(default='2021:10:11'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start',
            field=models.DateField(default='2021:10:10'),
        ),
    ]
