# Generated by Django 3.2.8 on 2021-10-21 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20211021_1908'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
