# Generated by Django 3.2.8 on 2021-10-22 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20211022_0924'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
